/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PrivateTodoListInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createTodo"
      | "getTodo"
      | "getTodoCount"
      | "getTodoTimestamps"
      | "protocolId"
      | "toggleTodo"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "TodoCreated" | "TodoToggled"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createTodo",
    values: [BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTodo",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTodoCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTodoTimestamps",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "toggleTodo",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "createTodo", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getTodo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTodoCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTodoTimestamps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "toggleTodo", data: BytesLike): Result;
}

export namespace TodoCreatedEvent {
  export type InputTuple = [
    user: AddressLike,
    todoIndex: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    todoIndex: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    todoIndex: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TodoToggledEvent {
  export type InputTuple = [
    user: AddressLike,
    todoIndex: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    todoIndex: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    user: string;
    todoIndex: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PrivateTodoList extends BaseContract {
  connect(runner?: ContractRunner | null): PrivateTodoList;
  waitForDeployment(): Promise<this>;

  interface: PrivateTodoListInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createTodo: TypedContractMethod<
    [
      encryptedId: BytesLike,
      encryptedCompleted: BytesLike,
      idProof: BytesLike,
      completedProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getTodo: TypedContractMethod<
    [user: AddressLike, index: BigNumberish],
    [
      [string, string, bigint] & {
        encryptedId: string;
        encryptedCompleted: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  getTodoCount: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getTodoTimestamps: TypedContractMethod<
    [user: AddressLike],
    [bigint[]],
    "view"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  toggleTodo: TypedContractMethod<
    [
      todoIndex: BigNumberish,
      encryptedCompleted: BytesLike,
      completedProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createTodo"
  ): TypedContractMethod<
    [
      encryptedId: BytesLike,
      encryptedCompleted: BytesLike,
      idProof: BytesLike,
      completedProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getTodo"
  ): TypedContractMethod<
    [user: AddressLike, index: BigNumberish],
    [
      [string, string, bigint] & {
        encryptedId: string;
        encryptedCompleted: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTodoCount"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTodoTimestamps"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "toggleTodo"
  ): TypedContractMethod<
    [
      todoIndex: BigNumberish,
      encryptedCompleted: BytesLike,
      completedProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "TodoCreated"
  ): TypedContractEvent<
    TodoCreatedEvent.InputTuple,
    TodoCreatedEvent.OutputTuple,
    TodoCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TodoToggled"
  ): TypedContractEvent<
    TodoToggledEvent.InputTuple,
    TodoToggledEvent.OutputTuple,
    TodoToggledEvent.OutputObject
  >;

  filters: {
    "TodoCreated(address,uint256,uint256)": TypedContractEvent<
      TodoCreatedEvent.InputTuple,
      TodoCreatedEvent.OutputTuple,
      TodoCreatedEvent.OutputObject
    >;
    TodoCreated: TypedContractEvent<
      TodoCreatedEvent.InputTuple,
      TodoCreatedEvent.OutputTuple,
      TodoCreatedEvent.OutputObject
    >;

    "TodoToggled(address,uint256,uint256)": TypedContractEvent<
      TodoToggledEvent.InputTuple,
      TodoToggledEvent.OutputTuple,
      TodoToggledEvent.OutputObject
    >;
    TodoToggled: TypedContractEvent<
      TodoToggledEvent.InputTuple,
      TodoToggledEvent.OutputTuple,
      TodoToggledEvent.OutputObject
    >;
  };
}
